# Generated by Django 5.0.3 on 2024-03-13 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_listed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
