# Generated by Django 5.0.2 on 2024-04-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_fooditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='foodimages'),
        ),
    ]
